apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-backend
  name: app-backend-preview
  namespace: ithome
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-backend
  name: app-backend-stable
  namespace: ithome
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-backend
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: ithome
spec:
  args:
  - name: pod-name
  - name: canary-hash
  metrics:
  - failureLimit: 3
    initialDelay: 30m
    interval: 1m
    name: success-rate
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |-
          sum(rate(
            http_server_requests_seconds_count{status!~"5.*", pod=~"{{args.pod-name}}.*", rollouts_pod_template_hash="{{args.canary-hash}}"}[5m]
          )) /
          sum(rate(
            http_server_requests_seconds_count{pod=~"{{args.pod-name}}.*", rollouts_pod_template_hash="{{args.canary-hash}}"}[5m]
          ))
    successCondition: isNaN(result[0]) || result[0] >= 0.95
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: app-backend
  name: app-backend
  namespace: ithome
spec:
  selector:
    matchLabels:
      app: app-backend
  strategy:
    canary:
      analysis:
        args:
        - name: pod-name
          value: app-backend
        - name: canary-hash
          valueFrom:
            podTemplateHashValue: Latest
        templates:
        - templateName: success-rate
      canaryService: app-backend-preview
      stableService: app-backend-stable
      steps:
      - setWeight: 10
      - pause:
          duration: 3m
      - setWeight: 33
      - pause:
          duration: 3m
      trafficRouting:
        nginx:
          additionalIngressAnnotations:
            canary-by-header: Canary
            canary-by-header-value: "true"
          stableIngress: primary-ingress
  template:
    metadata:
      labels:
        app: app-backend
        scrape: spring-boot-prometheus-exporter
    spec:
      containers:
      - image: luciferstut/app-backend-for-ithome2024:1.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 10
        name: apps
        ports:
        - containerPort: 8080
          name: web
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 300m
            memory: 512Mi
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 10
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    scrape: spring-boot-prometheus-exporter
  name: spring-boot-prometheus-exporter
  namespace: ithome
spec:
  podMetricsEndpoints:
  - interval: 10s
    path: /actuator/prometheus
    port: web
    relabelings:
    - sourceLabels:
      - __meta_kubernetes_pod_label_rollouts_pod_template_hash
      targetLabel: rollouts_pod_template_hash
  selector:
    matchLabels:
      scrape: spring-boot-prometheus-exporter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primary-ingress
  namespace: ithome
spec:
  rules:
  - host: day24.ithome.com
    http:
      paths:
      - backend:
          service:
            name: app-backend-stable
            port:
              number: 80
        pathType: ImplementationSpecific
