apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ithome

resources:
- rollout.yml
- stable-service.yml
- preview-service.yml
- primary-ingress.yml
- pod-monitor.yml
- analysis-template.yml

images:
- name: luciferstut/app-backend-for-ithome2024:none
  newTag: "1.1"