apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-backend
  name: product-backend
spec:
  selector:
    matchLabels:
      app: product-backend
  strategy: {}
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
      - image: luciferstut/product-backend-for-ithome2024:none
        name: apps
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "768Mi"
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        envFrom: # 將 ConfigMap 注入此容器
          - configMapRef:
              name: demo-config # 注入的 ConfigMap 名稱
