apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 關聯到的 resource 都會部署到 ithome namespace
namespace: ithome

resources: 
- ./configs
- ../../bases/app-backend
- ../../bases/product-backend

images:
- name: luciferstut/app-backend-for-ithome2024:none
  newTag: "1.0"
- name: luciferstut/product-backend-for-ithome2024:none
  newTag: "1.0"