apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
    tier: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: backend-nginx-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 8080;
            location / {
                proxy_pass http://db.ithome.svc.cluster.local:6379;
            }
        }
    }

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: backend
    tier: backend
  name: backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend
