apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  template:
    spec:
      containers:
        - name: apps
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"