apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

patches:
- target:
    kind: Deployment
    name: .*-backend
  path: api-rolling-update-strategy.yml
- target:
    kind: Deployment
    name: .*-schedule
  path: schedule-rolling-update-strategy.yml