apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-backend
  name: product-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: product-backend
