apiVersion: kustomize.config.k8s.io/v1alpha1  # <-- Component notation
kind: Component

patches:
- target:
    kind: Deployment
    labelSelector: monitor=spring-micrometer-monitor
  path: micro-profile-probes.yml
- target:
    kind: Deployment
    labelSelector: monitor=spring-micrometer-monitor
  path: scrape-metrics.yml

