apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-backend
  name: payment-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment-backend
